id = 1
title = "Cyber Academy: Introduction to Web"
short = "Intro To Web" 
date = "Monday 10/11 6:00PM-8:00PM PT"
description = """CCLE is down again? I wonder why? Whether you are an impulsive online shopper, chat on Discord, pay your credit cards, or simply want CCLE to work, these web applications are handling your data. Come to Cyberâ€™s first Fall workshop to learn the basics of web hacking in preparation for our future workshops.

RSVP on the Facebook Event
"""
link = ""
slides = "https://docs.google.com/presentation/d/1C_AzpSY-PW8oedeY-RWY4oqb3pqha6nh8512CTovg4o/edit?usp=sharing"
